export interface Commit {
  hash: string;
  message: string;
  date: string; // ISO string
  repo: string;
}

export interface Repository {
  name: string;
  description: string;
  language: string;
  stars: number;
  updatedAt: string;
}

export interface UserProfile {
  username: string;
  avatarUrl: string;
  name: string;
  bio: string;
  email?: string;
  phone?: string;
  location?: string;
  website?: string;
  linkedin?: string;
}

export interface ExperienceMonth {
  year: number;
  month: number; // 0-11
  commits: Commit[];
  summary?: string[]; // Generated by Gemini
  isGenerating?: boolean;
}

export interface CVData {
  profile: UserProfile;
  repos: Repository[];
  timeline: ExperienceMonth[];
  generatedSummary: string; // The main bio generated by Gemini
  skills: string[]; // Extracted or generated
  education: string[]; // List of education items
}

export enum AppState {
  LANDING,
  CONNECTING,
  FETCHING_DATA,
  MISSING_INFO,
  GENERATING_AI,
  READY,
}

export type ThemeColor = 'blue' | 'emerald' | 'violet' | 'rose' | 'amber';
export type ThemeFont = 'modern' | 'classic' | 'technical' | 'minimal';
export type AvatarShape = 'circle' | 'rounded' | 'square' | 'blob';

export interface CVTheme {
  color: ThemeColor;
  font: ThemeFont;
  shape: AvatarShape;
}

export type Language = 'en' | 'es' | 'de';